//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKULUYGULAMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int OgrenciId { get; set; }
        public string ogrenci_no { get; set; }
        public string ogrenci_tc { get; set; }
        public string ogrenci_ad { get; set; }
        public string ogrenci_soyad { get; set; }
        public string ogrenci_seviye { get; set; }
        public byte[] silindi { get; set; }
        public int SınıfSinifId { get; set; }
    
        public virtual Okul Okul { get; set; }
        public virtual Sınıf Sınıf { get; set; }
    }
}
