//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKULUYGULAMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Okul()
        {
            this.Ogrenciler = new HashSet<Ogrenciler>();
            this.Sınıf = new HashSet<Sınıf>();
        }
    
        public int OkulId { get; set; }
        public string okul_adi { get; set; }
        public byte[] silindi { get; set; }
        public string OkulOkulId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrenciler> Ogrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sınıf> Sınıf { get; set; }
    }
}
