using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace OKULUYGULAMA
{
    public partial class SINIF : Form
    {
        public SINIF()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Sınıf.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.Sınıf.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void SINIF_Load(object sender, EventArgs e)
        {
            // TODO: Bu kod satırı 'ogrenciListesiDataSet8.Sınıf' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
           this.sınıfTableAdapter.Fill(this.sınıfBindingSource);

        }
    }
}
